### ISSUE TITLE
flutter 能引入原生库吗

### ISSUE THREAD

**Issue by wangxuyang518** [7449/flutter_example#1]
如题

**Comment by 7449** [comment]
可以,你可以看下[开发flutter插件](https://flutter.io/developing-packages/)和[在不同的平台开发](https://flutter.io/platform-channels/)，`flutter`可以和`ios``android`平台进行通信,插件就是这样干的,但是你要考虑一点,开发插件需要兼顾`ios`和`android`,如果你只开发一个平台的那随便写，兼容性倒无所谓，[shared_preferences](https://pub.dartlang.org/packages/shared_preferences)就是一个很好的示例
